name: Build

on: [push]

jobs:
  build_ubuntu:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: kv_store_demo_ubuntu
          path: target/release/kv_store_demo
